  project:
    type: website

  format:
    html:
      theme: cosmo
      css: styles.css
      toc: true
      toc-depth: 4
      keep-md: true
      toc-location: right # Keeps TOC on the right like your examples
      toc-title: "Table of Contents"
      nbdev:
        show-docs: true
    commonmark: default

  website:
    favicon: images/peshbeen_favicon_64.png
    # navbar:
    #   title: false
    #   logo: images/logo_transparent.png
    #   left:
    #     - href: index.ipynb
    #       text: Home
    #     - href: install_guide.ipynb
    #       text: Install
    sidebar:
      logo: images/peshbeen_logo_transparent.png
      style: docked
      search: true
      contents:
        - text: "Quick Start"
          file: index.ipynb
        - text: "User Guide"
          file: user_guide.ipynb
        - text: "Model Zoo"
          file: guide/01_model_zoo.ipynb
        - text: "Stationarity & Detrending Strategies"
          file: guide/02_stationarity_detrending.ipynb
        - text: "Automatic Transformations"
          file: guide/03_auto_transformation.ipynb
        - text: "Probabilistic Forecasting"
          file: guide/04_prob_forecasting.ipynb
        - text: "Hyperparameter Tuning"
          file: guide/05_hyperparameter_tuning.ipynb
        - text: "API Reference"
          file: api/api.ipynb

      tools: 
        - icon: github
          href: https://github.com/mustafaslanCoto/peshbeen
      
    page-footer:
      center: 
        - text: "About"
        - text: "License"
        - text: "Trademark"

  metadata-files: [nbdev.yml]