  project:
    type: website

  format:
    html:
      theme: cosmo
      css: styles.css
      toc: true
      keep-md: true
      toc-location: right # Keeps TOC on the right like your examples
      toc-title: "Table of Contents"
      nbdev:
        show-docs: true
    commonmark: default

  website:
    favicon: images/favicon_64.png
    # navbar:
    #   title: false
    #   logo: images/logo_transparent.png
    #   left:
    #     - href: index.ipynb
    #       text: Home
    #     - href: install_guide.ipynb
    #       text: Install
    sidebar:
      logo: images/logo_transparent.png
      style: docked
      search: true
      contents:
        - text: "Quick Start"
          file: index.ipynb
        - section: "API Reference"
          contents:
            - section: "models"
              contents:
                - text: "naive"
                  file: modules/02_models/08_naive.ipynb
                - text: "ets"
                  file: modules/02_models/07_ets.ipynb
                - text: "arima"
                  file: modules/02_models/06_arima.ipynb
                - text: "ml_forecaster"
                  file: modules/02_models/01_ml_forecast.ipynb
                - text: "MsHmmRegression"
                  file: modules/02_models/02_ms_arr.ipynb
                - text: "ml_bidirect_forecaster"
                  file: modules/02_models/03_ml_mv_forecast.ipynb
                - text: "VARModel"
                  file: modules/02_models/04_var.ipynb
                - text: "MsHmmVar"
                  file: modules/02_models/05_ms_var.ipynb
            # - section: "model_selection"
              # contents:
            - text: "model_selection"
              file: modules/03_model_selection.ipynb
            - text: "probabilistic_forecasting"
              file: modules/04_prob_forecast.ipynb
            - text: "transformations"
              file: modules/05_transformations.ipynb
            - text: "metrics"
              file: modules/01_metrics.ipynb

      tools: 
        - icon: github
          href: https://github.com/mustafaslanCoto/peshbeen
      
    page-footer:
      center: 
        - text: "About"
        - text: "License"
        - text: "Trademark"

  metadata-files: [nbdev.yml]