  project:
    type: website

  format:
    html:
      theme: cosmo
      css: styles.css
      toc: true
      keep-md: true
      toc-location: right # Keeps TOC on the right like your examples
      toc-title: "Table of Contents"
      nbdev:
        show-docs: true
    commonmark: default

  website:
    title: "peshbeen"
    # navbar: 
    #   left:
    #     - text: "Examples"
    sidebar:
      style: docked
      search: true
      contents:
        - text: "Home"
          file: index.ipynb
        - text: "Installation Guide"
          file: install_guide.ipynb
        - section: "API Reference"
          contents:
            - section: "models"
              contents:
                - text: "ml_forecaster"
                  file: modules/02_models/01_ml_forecast.ipynb
                - text: "arima"
                  file: modules/02_models/06_arima.ipynb
                - text: "MsHmmRegression"
                  file: modules/02_models/02_ms_arr.ipynb
                - text: "ml_bidirect_forecaster"
                  file: modules/02_models/03_ml_mv_forecast.ipynb
                - text: "VARModel"
                  file: modules/02_models/04_var.ipynb
                - text: "MsHmmVar"
                  file: modules/02_models/05_ms_var.ipynb
            # - section: "model_selection"
              # contents:
            - text: "model_selection"
              file: modules/03_model_selection.ipynb
            # - section: "utils"
            #   contents:
            - text: "metrics"
              file: modules/01_metrics.ipynb
      
    page-footer:
      center: 
        - text: "About"
        - text: "License"
        - text: "Trademark"

  metadata-files: [nbdev.yml]