# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/modules/02_models/03_ml_mv_forecast.ipynb.

# %% ../../nbs/modules/02_models/03_ml_mv_forecast.ipynb #ef1fdc89
# from nbdev.showdoc import *
from __future__ import annotations
from typing import List, Dict, Optional, Callable, Tuple, Any, Union
from sklearn.base import clone
import numpy as np
import pandas as pd
import copy
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from ..transformations import (box_cox_transform, back_box_cox_transform,
                                      rolling_quantile,
                        expanding_mean, expanding_std, expanding_quantile)
from ..helpers import seasonal_diff, undiff_ts, invert_seasonal_diff
from ..model_selection import SplitTimeSeries
from ..statstools import lr_trend_model, forecast_trend
# dot not show warnings
import warnings
warnings.filterwarnings("ignore")
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from sklearn.compose import ColumnTransformer

class ml_mv_forecaster:
    def __init__(
        self,
        model: Any,
        target_cols: List[str],
        lags: Optional[Dict[str, Union[int, List[int]]]] = None,
        lag_transform: Optional[Dict[str, list]] = None,
        difference: Optional[Dict[str, int]] = None,
        seasonal_diff: Optional[Dict[str, int]] = None,
        trend: Optional[Dict[str, str]] = None,
        pol_degree: Optional[Union[int, Dict[str, int]]] = 1,
        ets_params: Optional[Dict[str, Any]] = None,
        change_points: Optional[Dict[str, List[int]]] = None,
        box_cox: Optional[Dict[str, Union[bool, float, int]]] = None,
        box_cox_biasadj: Optional[Dict[str, bool]] = None,
        cat_variables: Optional[List[str]] = None,
        categorical_encoder: Optional[Union[Dict[str, Any], Any]] = None
    ) -> None:
        
        """"
        Initialize the multi-target machine learning forecaster with specified transformations and model.

        Parameters
        ----------
        model : Any
            A scikit-learn compatible regression model instance (e.g. LGBMRegressor(), CatBoostRegressor(), LinearRegression(), etc.).
        target_cols : List[str]
            List of target variable names to forecast.
        lags : Optional[Dict[str, Union[int, List[int]]]], optional
            Dictionary specifying lag features to create for each target variable. The value can be an integer (number of lags) or a list of specific lag periods.
        lag_transform : Optional[Dict[str, list]], optional
            Dictionary specifying lag-based transformations to apply for each target variable. The value should be a list of transformation functions (e.g. rolling_mean, expanding_std) with their parameters encapsulated in the function instance.
        difference : Optional[Dict[str, int]], optional
            Dictionary specifying the order of ordinary differencing to apply for each target variable.
        seasonal_diff : Optional[Dict[str, int]], optional
            Dictionary specifying the order of seasonal differencing to apply for each target variable.
        trend : Optional[Dict[str, str]], optional
            Dictionary specifying the trend removal strategy for each target variable. Supported values are 'linear', 'ets', 'feature_lr', and 'feature_ets'.
        pol_degree : Optional[Union[int, Dict[str, int]]], optional
            Polynomial degree for linear trend removal. Can be a single integer applied to all targets or a dictionary specifying the degree for each target variable.
        ets_params : Optional[Dict[str, Any]]
            Dictionary specifying ETS model and fit parameters for each target variable when using 'ets' trend removal. Each value is a dictionary of parameters for the ExponentialSmoothing model and fitting process.
        change_points : Optional[Dict[str, List[int]]], optional
            Dictionary specifying change points for piecewise linear trend removal for each target variable. The value should be a list of integer indices where the trend slope can change.
        box_cox : Optional[Dict[str, Union[bool, float, int]]], optional
            Dictionary specifying whether to apply Box-Cox transformation for each target variable. The value can be a boolean (True to apply with lambda estimated from data, False to skip) or a float (specific lambda value to use).
        box_cox_biasadj : Optional[Dict[str, bool]], optional
            Dictionary specifying whether to apply bias adjustment when inverting Box-Cox transformation for each target variable.
        cat_variables : Optional[List[str]], optional
            List of categorical feature column names to encode. These will be shared across all target variables.
        categorical_encoder : Optional[Union[Dict[str, Any], Any]], optional
            A categorical encoder instance, or a single-entry dictionary mapping the target column to the encoder when the encoder requires access to the target variable during fitting (e.g. {target_col: MeanEncoder()}). If encoder requiring target access is provided directly without the dict format, first target column in target_cols will be used for fitting the encoder. For encoders that do not require target access, pass the encoder instance directly (e.g. OneHotEncoder()).
        -------
        None
        """

        self.model = model
        self.model_name = self.model.__class__.__name__
        self.target_cols = target_cols
        self.cat_variables = cat_variables
        if categorical_encoder is not None:
            if isinstance(categorical_encoder, dict):
                if len(categorical_encoder) != 1:
                    raise ValueError("If categorical_encoder is a dict, it must contain exactly one entry mapping a target column to the encoder instance.")
                encoder_target_col, encoder = next(iter(categorical_encoder.items())) # get the single key-value pair from the dict
                if encoder_target_col not in self.target_cols:
                    raise ValueError("The single key in categorical_encoder must be one of target_cols.")
                self.cat_encoder_key = encoder_target_col
                self.cat_encoder = encoder
            else:
                self.cat_encoder = categorical_encoder
                self.cat_encoder_key = self.target_cols[0] # just get one of the target columns since we are not using the encoder in a target-specific way, but we will check for target access requirement later when we fit the encoder

        else:
            # self.cat_encoder_key = None
            self.cat_encoder = None



        if self.cat_variables is not None and self.cat_encoder is None: # if we have categorical variables but no encoder specified, model must be able to handle categorical features natively (e.g. LGBM or CatBoost)
            if not (self.model_name in ['LGBMRegressor', 'CatBoostRegressor']):
                raise ValueError("Model must be LGBMRegressor or CatBoostRegressor to handle categorical variables without a specified encoder (you can also specify an encoder like OneHotEncoder or MeanEncoder to use with other models).")
            
        self.cps = change_points

        # ── lags ──────────────────────────────────────────────────────────────
        self.n_lag = {}
        if lags is not None:
            if not isinstance(lags, dict):
                raise TypeError("lags must be a dict keyed by target column name.")
            for col, v in lags.items():
                if isinstance(v, int):
                    self.n_lag[col] = list(range(1, v + 1))
                elif isinstance(v, list):
                    self.n_lag[col] = v
                else:
                    raise TypeError(f"lags['{col}'] must be int or list of ints.")

        # ── lag_transform ─────────────────────────────────────────────────────
        if lag_transform is not None:
            if not isinstance(lag_transform, dict):
                raise TypeError("lag_transform must be a dict keyed by target column name.")
            self.lag_transform = lag_transform
        else:
            self.lag_transform = None

        # ── differencing ──────────────────────────────────────────────────────
        self.diffs = {col: None for col in target_cols}
        if difference is not None:
            if not isinstance(difference, dict):
                raise TypeError("difference must be a dict keyed by target column name.")
            self.diffs.update(difference)

        # ── seasonal differencing ─────────────────────────────────────────────
        self.season_diffs = {col: None for col in target_cols}
        if seasonal_diff is not None:
            if not isinstance(seasonal_diff, dict):
                raise TypeError("seasonal_diff must be a dict keyed by target column name.")
            self.season_diffs.update(seasonal_diff)

        # ── trend ─────────────────────────────────────────────────────────────
        self.trend = trend
        if trend is not None and not isinstance(trend, dict):
            raise TypeError("trend must be a dict keyed by target column name.")
        

        if self.trend is not None and "ets" in trend.values():
            # ── ets params ────────────────────────────────────────────────────────────
            CONSTRUCTOR_PARAMS = {
                "trend", "damped_trend", "seasonal", "seasonal_periods",
                "initialization_method", "initial_level", "initial_trend",
                "initial_seasonal", "bounds", "dates", "freq", "missing",
            }
            FIT_PARAMS = {
                "optimized", "smoothing_level", "smoothing_trend", "smoothing_seasonal",
                "damping_trend", "remove_bias", "start_params", "method",
                "minimize_kwargs", "use_brute",
            }

            self.ets_model: Dict[str, dict] = {}
            self.ets_fit: Dict[str, dict] = {}
            if ets_params is not None:
                if not isinstance(ets_params, dict):
                    raise TypeError("ets_params must be a dict keyed by target column name.")
                for col, ttype in trend.items():
                    if ttype == "ets":
                        col_params = ets_params.get(col, {})  # flat dict per target, same as univariate
                        if not isinstance(col_params, dict):
                            raise TypeError(f"ets_params['{col}'] must be a flat dict of ETS parameters.")
                        self.ets_model[col] = {k: v for k, v in col_params.items() if k in CONSTRUCTOR_PARAMS}
                        self.ets_fit[col]   = {k: v for k, v in col_params.items() if k in FIT_PARAMS}
            else:
                # default empty dicts for all ETS targets
                for col, ttype in trend.items():
                    if ttype == "ets":
                        self.ets_model[col] = {}
                        self.ets_fit[col]   = {}

        # ── polynomial degree ─────────────────────────────────────────────────
        if isinstance(pol_degree, int):
            self.pol = {col: pol_degree for col in target_cols}
        elif isinstance(pol_degree, dict):
            self.pol = {col: pol_degree.get(col, 1) for col in target_cols}
        else:
            raise ValueError("pol_degree must be an int or a dict.")

        # ── polynomial degree ─────────────────────────────────────────────────
        if isinstance(pol_degree, int):
            self.pol = {col: pol_degree for col in target_cols}
        elif isinstance(pol_degree, dict):
            self.pol = {col: pol_degree.get(col, 1) for col in target_cols}
        else:
            raise ValueError("pol_degree must be an int or a dict.")

        # ── box-cox ───────────────────────────────────────────────────────────
        # initialise biasadj regardless of box_cox
        if isinstance(box_cox_biasadj, bool):
            self.biasadj = {col: box_cox_biasadj for col in target_cols}
        elif isinstance(box_cox_biasadj, dict):
            self.biasadj = {col: box_cox_biasadj.get(col, False) for col in target_cols}
        else:
            self.biasadj = {col: False for col in target_cols}

        if box_cox is not None:
            self.box_cox: Dict[str, bool] = {}
            self.lamdas: Dict[str, Optional[float]] = {col: None for col in target_cols}
            
            if isinstance(box_cox, bool):          # ← bool before (float, int)
                self.box_cox = {col: box_cox for col in target_cols}
            elif isinstance(box_cox, (float, int)):
                self.box_cox = {col: True for col in target_cols}
                self.lamdas = {col: box_cox for col in target_cols}
            elif isinstance(box_cox, dict):
                for col, val in box_cox.items():
                    if isinstance(val, bool):          # ← bool before (float, int)
                        self.box_cox[col] = val
                        self.lamdas[col] = None
                    elif isinstance(val, (float, int)):
                        self.box_cox[col] = True
                        self.lamdas[col] = val
                    else:
                        raise ValueError(
                            f"Invalid value for box_cox['{col}']: must be bool or float."
                        )
            else:
                raise TypeError(
                    "box_cox must be a bool, float, or dict keyed by target column name."
                )
            
        else:
            self.box_cox = box_cox

        # ── placeholders set during fit ───────────────────────────────────────
        self.model_fits: Dict[str, Any] = {}
        self.y_dict: Dict[str, pd.Series] = {}

    # ─────────────────────────────────────────────────────────────────────────
    # DATA PREPARATION
    # ─────────────────────────────────────────────────────────────────────────

    def data_prep(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Apply all preprocessing transformations to df and return the cleaned DataFrame.
        """
        dfc = df.copy()

        # ── categorical encoding ──────────────────────────────────────────────
        if self.cat_variables is not None:
            dfc = self.create_encoded_features(dfc)

        if not all(col in dfc.columns for col in self.target_cols):
            return dfc.dropna()
        
        self.orig_target = dfc[self.target_cols].values
        # ── Box-Cox ───────────────────────────────────────────────────────────
        if self.box_cox is not None:
            self.is_zeros: Dict[str, bool] = {} # track if shift was applied for each target
            self.trans_data: Dict[str, np.ndarray] = {} # store transformed data for in-sample residual calculations
            for col in self.target_cols:
                if self.box_cox.get(col, False): # only apply if box_cox is True for this target
                    self.is_zeros[col] = (dfc[col] < 1).any()
                    trans_data, self.lamdas[col] = box_cox_transform(
                        x=dfc[col], shift=self.is_zeros[col], box_cox_lmda=self.lamdas[col]
                    ) # returns transformed data and lambda. If lambda is not provided, it is estimated from the data.
                    dfc[col] = trans_data
                    self.trans_data[col] = trans_data

        # ── Trend removal ─────────────────────────────────────────────────────
        if self.trend is not None:
            self.len = len(df)
            self.orig_targets: Dict[str, pd.Series] = {}
            self.trend_models: Dict[str, Any] = {}
            self.X_trend_forecasts: Dict[str, np.ndarray] = {}  # for feature_lr

            for col, ttype in self.trend.items():
                self.orig_targets[col] = dfc[col].copy()

                if ttype == "linear":
                    bps = self.cps.get(col) if self.cps else None
                    if bps:
                        trend_vals, model_fit, X_trend = lr_trend_model(
                            self.orig_targets[col], degree=self.pol[col],
                            breakpoints=bps, type='piecewise'
                        )
                    else:
                        trend_vals, model_fit, X_trend = lr_trend_model(
                            self.orig_targets[col], degree=self.pol[col])
                    self.trend_models[col] = (model_fit, X_trend)
                    dfc[col] = dfc[col] - trend_vals

                elif ttype == "ets":
                    model_fit = ExponentialSmoothing(
                        self.orig_targets[col], **self.ets_model[col]
                    ).fit(**self.ets_fit[col])
                    dfc[col] = dfc[col] - model_fit.fittedvalues.values
                    self.trend_models[col] = model_fit

                else:
                    raise ValueError(
                        f"Unknown trend type '{ttype}' for '{col}'. "
                        "Use 'linear' or 'ets'."
                    )

        # ── Ordinary differencing ─────────────────────────────────────────────
        self.origs: Dict[str, list] = {}
        for col, d in self.diffs.items():
            if d is not None:
                self.origs[col] = dfc[col].tolist()
                dfc[col] = np.diff(dfc[col], n=d, prepend=np.repeat(np.nan, d))

        # ── Seasonal differencing ─────────────────────────────────────────────
        self.orig_ds: Dict[str, list] = {}
        for col, s in self.season_diffs.items():
            if s is not None:
                self.orig_ds[col] = dfc[col].tolist()
                dfc[col] = seasonal_diff(dfc[col], s)

        # ── Lag features ──────────────────────────────────────────────────────
        for col, lags in self.n_lag.items():
            for lg in lags:
                dfc[f"{col}_lag_{lg}"] = dfc[col].shift(lg)

        # ── Lag transforms ────────────────────────────────────────────────────
        if self.lag_transform is not None:
            for idx, (col, funcs) in enumerate(self.lag_transform.items()):
                for func in funcs:
                    if isinstance(func, (expanding_std, expanding_mean)):
                        dfc[f"trg{idx}_{func.__class__.__name__}_shift_{func.shift}"] = func(dfc[col])
                    elif isinstance(func, expanding_quantile):
                        dfc[f"trg{idx}_{func.__class__.__name__}_shift_{func.shift}_q{func.quantile}"] = func(dfc[col])
                    elif isinstance(func, rolling_quantile):
                        dfc[f"trg{idx}_{func.__class__.__name__}_{func.window_size}_shift_{func.shift}_q{func.quantile}"] = func(dfc[col])
                    else:
                        dfc[f"trg{idx}_{func.__class__.__name__}_{func.window_size}_shift_{func.shift}"] = func(dfc[col])

        return dfc.dropna()
    
    # ─────────────────────────────────────────────────────────────────────────
    # ENCODE CATEGORICAL FEATURES
    # ─────────────────────────────────────────────────────────────────────────

    def create_encoded_features(self,
                    df: pd.DataFrame
                    ) -> pd.DataFrame:
        
        ## make sure categorical variables are treated as category dtype for encoding
        for col in self.cat_variables:
            df[col] = df[col].astype('category')
        ## if fit has been called but forecat has not been called yet, we can fit the encoder on the training data and store it for use during forecasting

        if self.cat_encoder is not None:
            # if self.target_col in df.columns and not hasattr(self, "model_fit"):
            if all(col in df.columns for col in self.target_cols): # if we have target values, we are in the fit stage and can fit the encoder on the training data (if not already fitted) and then transform the data for model fitting
                num_cols = [c for c in df.columns if c not in self.cat_variables + self.target_cols]

                # pass_cols = self.cat_variables + num_cols
                self.preprocess = ColumnTransformer(
                    transformers=[("cat", self.cat_encoder, self.cat_variables), ("num", "passthrough", num_cols)],
                    remainder="drop",
                    verbose_feature_names_out=False
                ).set_output(transform="pandas")

                X_train = self.preprocess.fit_transform(df.drop(columns=self.target_cols), y=df[self.cat_encoder_key])
                return pd.concat([df[self.target_cols], X_train], axis=1)
            
            else: # if we do not have target values, we are in the forecast stage and can just transform the data using the already fitted encoder
                return self.preprocess.transform(df)
        else:
            return df # if no encoder, return original df (but with categorical variables converted to category dtype in case model can handle them natively, e.g. LGBM or CatBoost)

    # ─────────────────────────────────────────────────────────────────────────
    # FIT
    # ─────────────────────────────────────────────────────────────────────────

    def fit(self,
            df: pd.DataFrame
            ) -> None:
        
        """
        Fit the model to the data passed in df

        Parameters
        ----------
        df : pd.DataFrame
            Training DataFrame containing all target and feature columns.

        Returns
        -------
        None
        """

        model_df = self.data_prep(df)
        X = model_df.drop(columns=self.target_cols)
        self.X = X  # store feature matrix for AIC/BIC properties

        # prepare targets once
        self.y_dict = {col: model_df[col] for col in self.target_cols}

        # decide fit kwargs once
        fit_kwargs = {}
        if self.cat_encoder is None:
            if self.model_name  == 'LGBMRegressor':
                fit_kwargs = {"categorical_feature": self.cat_variables}
            elif self.model_name == 'CatBoostRegressor':
                fit_kwargs = {"cat_features": self.cat_variables, "verbose": False}

        # fit one model per target
        self.model_fits = {}
        for col, y in self.y_dict.items():
            m = clone(self.model)
            self.model_fits[col] = m.fit(X, y, **fit_kwargs)

    # ─────────────────────────────────────────────────────────────────────────
    # IN-SAMPLE PREDICTIONS
    # ─────────────────────────────────────────────────────────────────────────

    def predict_in_sample(self) -> np.ndarray:
        """
        Generate in-sample predictions and residuals for the training data. This can be useful for diagnostic purposes, such as checking for patterns in the residuals or calculating in-sample performance metrics.

        Returns
        -------
        np.ndarray
            In-sample fitted values and residuals for the training data.
        """

        fit_len = self.X.shape[0]
        self.fitted_values = {col: np.array(self.model_fits[col].predict(self.X)) for col in self.target_cols}
        
        self.in_samp_resids = {col: self.y_dict[col].to_numpy() - self.fitted_values[col] for col in self.target_cols}
        self.fitted_values = {col: self.orig_target[-fit_len:, i] - self.in_samp_resids[col] for i, col in enumerate(self.target_cols)}
        if self.box_cox is not None:
            for i, col in enumerate(self.target_cols):
                if self.box_cox.get(col, False):
                    bc_fitted = self.trans_data[col][-fit_len:] + self.in_samp_resids[col]
                    self.fitted_values[col] = back_box_cox_transform(
                        y_pred=bc_fitted, lmda=self.lamdas[col],
                        shift=self.is_zeros.get(col, False), box_cox_biasadj=self.biasadj[col]
                    )
                    self.in_samp_resids[col] = self.orig_target[-fit_len:, i] - self.fitted_values[col]

    # ─────────────────────────────────────────────────────────────────────────
    # FORECAST
    # ─────────────────────────────────────────────────────────────────────────

    def forecast(
        self,
        H: int,
        exog: Optional[pd.DataFrame] = None
    ) -> Dict[str, np.ndarray]:
        
        """
        Generate forecasts for H future time steps.

        Parameters
        ----------
        H : int
            Forecast horizon (number of steps to forecast ahead).
        exog : Optional[pd.DataFrame], optional
            Future exogenous regressors (must contain at least H rows).
            
        Returns
        -------
        Dict[str, np.ndarray]
            A dictionary where keys are target column names and values are arrays of H forecasted values for each target variable.
        """

        # Prepare exog if provided
        if exog is not None:
            if self.cat_variables is not None:
                exog = self.data_prep(exog)
        # Rolling history for each target (used to build lag features recursively)
        y_lists: Dict[str, list] = {col: self.y_dict[col].tolist() for col in self.target_cols}

        # ── Pre-compute trend forecasts ───────────────────────────────────────
        trend_forecasts: Dict[str, np.ndarray] = {}
        X_trend_forecasts: Dict[str, np.ndarray] = {}

        if self.trend is not None:
            for col, ttype in self.trend.items():
                if ttype == "linear":
                    model_fit, _ = self.trend_models[col]
                    bps = self.cps.get(col) if self.cps else None # get breakpoints for this target if they exist, if not use None
                    tf, X_tf = forecast_trend(
                        model=model_fit, H=H, start=self.len,
                        degree=self.pol[col], breakpoints=bps
                    )
                    trend_forecasts[col] = tf
                    X_trend_forecasts[col] = X_tf
                elif ttype == "ets":
                    trend_forecasts[col] = np.array(self.trend_models[col].forecast(H))

        # ── Recursive forecast loop ───────────────────────────────────────────
        raw_forecasts: Dict[str, list] = {col: [] for col in self.target_cols}

        for t in range(H):
            # Exogenous features for step t
            x_var = exog.iloc[t, :].tolist() if exog is not None else []

            # Lag features
            inp_lag = []
            for col, lags in self.n_lag.items():
                inp_lag.extend([y_lists[col][-lg] for lg in lags])

            # Lag-transform features
            transform_lag = []
            if self.lag_transform is not None:
                for col, funcs in self.lag_transform.items():
                    series_array = np.array(y_lists[col])
                    for func in funcs:
                        transform_lag.append(func(series_array, is_forecast=True).to_numpy()[-1])

            inp = x_var + inp_lag + transform_lag
            df_inp = pd.DataFrame(np.array(inp).reshape(1, -1), columns=self.X.columns)

            if (self.model_name in ['LGBMRegressor', 'CatBoostRegressor']) and self.cat_encoder is None:
                for c in df_inp.columns:
                    if c in (self.cat_variables or []):
                        df_inp[c] = df_inp[c].astype(int).astype('category')
                    else:
                        df_inp[c] = df_inp[c].astype('float64')

            # Predict each target and update its rolling history
            for col in self.target_cols:
                pred = self.model_fits[col].predict(df_inp)[0]
                raw_forecasts[col].append(pred)
                y_lists[col].append(pred)

        # ── Post-processing (mirrors VARModel.forecast) ───────────────────────
        forecasts: Dict[str, np.ndarray] = {col: np.array(raw_forecasts[col]) for col in self.target_cols}

        # Add back removed trend
        if self.trend is not None:
            for col, ttype in self.trend.items():
                if ttype in ("linear", "ets"):
                    forecasts[col] = forecasts[col] + trend_forecasts[col]

        # Invert seasonal differencing
        for col, s in self.season_diffs.items():
            if s is not None:
                forecasts[col] = invert_seasonal_diff(self.orig_ds[col], forecasts[col], s)

        # Invert ordinary differencing
        for col, d in self.diffs.items():
            if d is not None:
                forecasts[col] = undiff_ts(self.origs[col], forecasts[col], d)

        # Non-negativity
        for col in forecasts:
            forecasts[col] = np.array([max(0, x) for x in forecasts[col]])

        # Invert Box-Cox
        if self.box_cox is not None:
            for col in self.target_cols:
                if self.box_cox.get(col, False):
                    forecasts[col] = back_box_cox_transform(
                        y_pred=forecasts[col],
                        lmda=self.lamdas[col],
                        shift=self.is_zeros.get(col, False),
                        box_cox_biasadj=self.biasadj[col]
                )

        return forecasts

    # ─────────────────────────────────────────────────────────────────────────
    # INFORMATION CRITERIA  (mirrors ml_forecaster AIC/BIC properties)
    # ─────────────────────────────────────────────────────────────────────────

    def _k(self) -> int:
        """Number of model parameters (approximate)."""
        base = self.X.shape[1]
        if isinstance(self.model, (LinearRegression, Ridge, Lasso, ElasticNet)):
            return base + 2   # coefficients + intercept + variance
        return base + 1       # coefficients + variance

    def _ic_base(self, col: str):
        k = self._k()
        n = len(self.y_dict[col])
        rss = np.sum((self.y_dict[col].to_numpy() - self.model_fits[col].predict(self.X)) ** 2)
        return k, n, rss

    @property
    def aic(self) -> Dict[str, float]:
        """AIC per target variable."""
        out = {}
        for col in self.target_cols:
            k, n, rss = self._ic_base(col)
            out[col] = n * np.log(rss / n) + 2 * k
        return out

    @property
    def aicc(self) -> Dict[str, float]:
        """AICc per target variable."""
        out = {}
        for col in self.target_cols:
            k, n, rss = self._ic_base(col)
            aic = n * np.log(rss / n) + 2 * k
            out[col] = aic + (2 * k * (k + 1)) / (n - k - 1)
        return out

    @property
    def bic(self) -> Dict[str, float]:
        """BIC per target variable."""
        out = {}
        for col in self.target_cols:
            k, n, rss = self._ic_base(col)
            out[col] = n * np.log(rss / n) + k * np.log(n)
        return out

    @property
    def hqc(self) -> Dict[str, float]:
        """Hannan-Quinn criterion per target variable."""
        out = {}
        for col in self.target_cols:
            k, n, rss = self._ic_base(col)
            out[col] = n * np.log(rss / n) + 2 * k * np.log(np.log(n))
        return out

    def copy(self):
        return copy.deepcopy(self)

    def cross_validate(self,
                       df: pd.DataFrame,
                       target_col: str,
                       cv_split: int,
                       test_size: int,
                       metrics: List[Callable],
                       step_size: int = 1,
                       h_split_point: Optional[int] = None
                       ) -> Union[pd.DataFrame, Tuple[pd.DataFrame, pd.DataFrame]]:
        """
        Perform cross-validation.

        Parameters
        ----------
        df : pd.DataFrame
            Input dataframe.
        target_col : str
            Target variable for evaluation.
        cv_split : int
            Number of cross-validation folds.
        test_size : int
            Test size per fold.
        metrics : list of callable
            Metric functions (e.g. ``[MAE, RMSE]``) used to evaluate forecast accuracy across folds. Call ``.cv_summary()`` after cross-validation to retrieve the aggregated scores.
        step_size : int, optional
            Step size for rolling window. Default is 1.
        h_split_point : int, optional
            Point to split the test set for separate evaluation. Default is None.
    
        Returns
        -------
        pd.DataFrame
            DataFrame with overall performance metrics averaged across folds. If h_split_point is provided, also includes separate performance before and after the split point.
        """

        cv_df_ = pd.DataFrame()
        tscv = SplitTimeSeries(n_splits=cv_split, test_size=test_size, step_size=step_size)
        metrics_dict = {m.__name__: [] for m in metrics}
        if h_split_point is not None:
            metrics_dict1 = {m.__name__: [] for m in metrics}
            metrics_dict2 = {m.__name__: [] for m in metrics}

        for idx, (train_index, test_index) in enumerate(tscv.split(df)):
            train, test = df.iloc[train_index], df.iloc[test_index]
            x_test, y_test = test.drop(columns=self.target_cols), np.array(test[target_col])
            self.fit(train)
            exog_t = x_test if x_test.shape[1] > 0 else None
            forecasts = self.forecast(test_size, exog_t)[target_col]

            for m in metrics:
                if m.__name__ in ["MASE", "SMAE", "SRMSE", "RMSSE"]:
                    eval_val = m(y_test, forecasts, train[target_col])
                else:
                    eval_val = m(y_test, forecasts)
                metrics_dict[m.__name__].append(eval_val)
            if h_split_point is not None and isinstance(h_split_point, int):
                y_test_1, y_test_2 = y_test[:h_split_point], y_test[h_split_point:]
                bb_forecast_1, bb_forecast_2 = forecasts[:h_split_point], forecasts[h_split_point:]
                for m in metrics:
                    if m.__name__ in ['MASE', 'SMAE', 'SRMSE', 'RMSSE']:
                        eval_val1 = m(y_test_1, bb_forecast_1, np.array(train[self.target_cols]))
                        eval_val2 = m(y_test_2, bb_forecast_2, np.array(train[self.target_cols]))
                    else:
                        eval_val1 = m(y_test_1, bb_forecast_1)
                        eval_val2 = m(y_test_2, bb_forecast_2)
                    metrics_dict1[m.__name__].append(eval_val1)
                    metrics_dict2[m.__name__].append(eval_val2)

            ## store results for this split
            all_forecasts = self.forecast(test_size, exog_t)
            actuals = {f"actual_{col}": test[col].values for col in self.target_cols}
            all_forecasts_dict = {f"forecast_{col}": all_forecasts[col] for col in self.target_cols}
            split_results = {"cutoff": np.repeat(test.index[0], len(test)), "index": test.index,
                            "split": np.repeat(f"fold_{idx+1}", len(test))}
            
            split_results.update(actuals)
            split_results.update(all_forecasts_dict)

            cv_df_ = pd.concat([cv_df_, pd.DataFrame(split_results)], ignore_index=True)
                
        overall_performance = [[m.__name__, np.mean(metrics_dict[m.__name__])] for m in metrics]
        overall_performance = pd.DataFrame(overall_performance).rename(columns={0: "eval_metric", 1: "score"})
        if h_split_point is not None and isinstance(h_split_point, int):
            performance_1 = [[m.__name__, np.mean(metrics_dict1[m.__name__])] for m in metrics]
            performance_2 = [[m.__name__, np.mean(metrics_dict2[m.__name__])] for m in metrics]
            overall_performance = pd.DataFrame(overall_performance).rename(columns={0: "eval_metric", 1: "score"})
            perf_1_df = pd.DataFrame(performance_1).rename(columns={0: "eval_metric", 1: f"score_before_{h_split_point}"})
            perf_2_df = pd.DataFrame(performance_2).rename(columns={0: "eval_metric", 1: f"score_after_{h_split_point}"})
            # merge all three dataframes
            overall_performance = overall_performance.merge(perf_1_df, on="eval_metric").merge(perf_2_df, on="eval_metric")
            
        self.cv_summary = overall_performance
        return cv_df_

    # a name for the class that is more descriptive of its purpose
    def get_name(self):
        return "ml_mv_forecaster"



# %% auto #0
__all__ = ['ml_mv_forecaster']
