name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: [uses: answerdotai/workflows/quarto-ghp@master]
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Fix nbdev dependencies
#         run: pip install -Uq --force-reinstall 'nbdev<3' execnb
#       - uses: answerdotai/workflows/quarto-ghp@master


